site_name: PiStat
repo_url: https://github.com/NateZimmer/piStat

dev_addr: 127.0.0.1:8005

nav:
- Introduction: 
    - Home: index.md
- Theory:
    - Thermal Model: Thermal/Thermal.md

use_directory_urls: false
edit_uri: 'tree/master/docs_source/docs'

theme:
    name: readthedocs
    highlightjs: true
    
markdown_extensions:
  - admonition
  - pymdownx.arithmatex
  - toc:
      permalink: true

extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'